% psychMLEfitSimul   Simulates a GLM for Psychometric functions and then fits using  using LSE and MLE
% function psychfit(xdata,ydata,plotflag)
%
% Execute simulation script and then fit
global t X     % Trial no,  response {0,1}
addpath('C:\Users\pavelm\Documents\Matlab_local\tools_local');
if ~exist('plotflag','var') plotflag = false; end  % plotflag = 1;
rseed = 38714;  % rng('default');
rng(rseed);     % rng('default');
verbose = true;
ptype = 'insight';  
%ptype = 'logit';

% Learning block parameters
n = 40;
t0 = 1:n;   % Trial number
cg = 0.25;  % Guessing baseline
cl = 0.9;   % 1 - P{Errors} after completed learning
Nr = 1;    % Number of repetitions for simulation  Nr = 1;

% Simulate set of responses generated by a psychometric function
psycho_simul
% Compute MLE fits to both the IRT and Step versions
psycho_fit

% The outcome are two likelihood functions - they should probably be
% divided by the degrees of freedom, but ...
likmax_irt
likmax_step